from typing import Any

class Vec3f:
    def __init__(self, *args: float) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class Vec3d:
    def __init__(self, *args: float) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class Matrix4d:
    def __init__(self, *args: object) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __mul__(self, other: Matrix4d) -> Matrix4d: ...
    def __getitem__(self, index: tuple[int, int]) -> float: ...

class Quatf:
    def __init__(self, *args: object) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class Rotation:
    def __init__(self, *args: object) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
