from typing import Any

class Stage:
    def __getattr__(self, name: str) -> Any: ...
    @staticmethod
    def CreateNew(path: str) -> Stage: ...
    @staticmethod
    def Open(path: str) -> Stage: ...

class Prim:
    def __getattr__(self, name: str) -> Any: ...
