from typing import Any, Self

from pxr import Usd

Tokens: Any

def SetStageMetersPerUnit(stage: Usd.Stage, metersPerUnit: float) -> bool: ...
def GetStageMetersPerUnit(stage: Usd.Stage) -> float: ...
def SetStageUpAxis(stage: Usd.Stage, axis: str) -> bool: ...
def GetStageUpAxis(stage: Usd.Stage) -> str: ...

class _SchemaBase:
    def __getattr__(self, name: str) -> Any: ...
    @classmethod
    def Define(cls, stage: Usd.Stage, path: str) -> Self: ...
    def GetPrim(self) -> Usd.Prim: ...

class Xform(_SchemaBase): ...
class Scope(_SchemaBase): ...

class Mesh(_SchemaBase):
    @staticmethod
    def ComputeExtent(points: object) -> Any: ...

class Xformable(_SchemaBase):
    def __init__(self, prim: Usd.Prim) -> None: ...
