from typing import Any, Self

from pxr import Usd

class _SchemaBase:
    def __getattr__(self, name: str) -> Any: ...
    @classmethod
    def Define(cls, stage: Usd.Stage, path: str) -> Self: ...
    @classmethod
    def Get(cls, stage: Usd.Stage, path: object) -> Self: ...
    @classmethod
    def Apply(cls, prim: Usd.Prim) -> Self: ...
    def GetPrim(self) -> Usd.Prim: ...

class ArticulationRootAPI(_SchemaBase): ...
class RigidBodyAPI(_SchemaBase): ...
class FixedJoint(_SchemaBase): ...
class RevoluteJoint(_SchemaBase): ...
class PrismaticJoint(_SchemaBase): ...
