from typing import Any

class ValidationRegistry:
    def __getattr__(self, name: str) -> Any: ...

class ValidationContext:
    def __init__(self, *args: object) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
